# Generated by Django 5.2.17 on 2026-09-16 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="e-posta"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Kullanıcı adı 3–30 karakter olmalı ve yalnızca harf, rakam ve alt çizgi içermelidir.",
                        regex="^[a-zA-Z0-9_]{3,30}$",
                    )
                ],
                verbose_name="kullanıcı adı",
            ),
        ),
    ]
