# Generated by Django 5.2.17 on 2026-09-16 20:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=120,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=1000)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("phone", "Akıllı Telefon"),
                            ("laptop", "Dizüstü Bilgisayar"),
                            ("tablet", "Tablet"),
                            ("headphone", "Kulaklık"),
                            ("smartwatch", "Akıllı Saat"),
                            ("gaming", "Oyun & Konsol"),
                            ("camera", "Kamera"),
                            ("tv", "TV & Monitör"),
                            ("pc_part", "Bilgisayar Parçası"),
                            ("other", "Diğer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(
                                Decimal("10000000")
                            ),
                        ],
                    ),
                ),
                ("currency", models.CharField(default="TRY", max_length=3)),
                ("features", models.TextField()),
                (
                    "product_url",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.URLValidator(schemes=["https"])
                        ],
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="polls.poll",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anon_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "value",
                    models.SmallIntegerField(
                        choices=[(1, "Buna değer"), (-1, "Buna değmez")]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="polls.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("poll", "position"), name="unique_position_per_poll"
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("product", "user"),
                name="unique_vote_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("anon_id__isnull", False)),
                fields=("product", "anon_id"),
                name="unique_vote_per_anon",
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("anon_id__isnull", True), ("user__isnull", False)),
                    models.Q(("anon_id__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="vote_has_exactly_one_voter",
            ),
        ),
    ]
