# Generated by Django 5.2.17 on 2026-09-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_voteattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="ip_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
