# Generated by Django 5.2.17 on 2026-09-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_poll_hide_results_until_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
