# Generated by Django 5.2.17 on 2026-09-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_poll_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.TextField(blank=True),
        ),
    ]
