# Generated by Django 5.2.17 on 2026-09-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_product_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="budget_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("economic", "Ekonomik"),
                    ("mid", "Orta segment"),
                    ("premium", "Üst segment"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="usage_purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gaming", "Oyun"),
                    ("school", "Okul"),
                    ("work", "İş"),
                    ("daily", "Günlük kullanım"),
                    ("other", "Diğer"),
                ],
                max_length=20,
            ),
        ),
    ]
