# Generated by Django 5.2.17 on 2026-09-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_poll_budget_tier_poll_usage_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
