import type { Poll } from "./types";

export const mockPolls: Poll[] = [
  {
    id: 1,
    title: "Bu bütçeye en iyi oyun telefonu hangisi?",
    description:
      "15.000 TL altında, ağır oyunları takılmadan oynayabileceğim bir telefon arıyorum.",
    category: "telefon",
    usagePurpose: "oyun",
    budgetTier: "orta",
    authorUsername: "ferhan",
    createdAt: "2026-09-16T10:00:00Z",
    expiresAt: "2026-09-25T10:00:00Z",
    isActive: true,
    isExpired: false,
    hideResultsUntilVote: false,
    viewCount: 482,
    totalVotes: 96,
    todayVotes: 12,
    minPrice: 12999,
    maxPrice: 14999,
    products: [
      {
        id: 1,
        name: "Redmi Note 13 Pro",
        price: 12999,
        imageUrl: null,
        productUrl: "https://example.com/redmi-note-13-pro",
        features: ["120Hz AMOLED ekran", "5000 mAh batarya", "67W hızlı şarj"],
        attributes: { RAM: "8 GB", Depolama: "256 GB", İşlemci: "Snapdragon 7s Gen 2" },
        worthCount: 41,
        notWorthCount: 9,
        worthRatio: 82,
        showResults: true,
        userVote: null,
        isCheapest: true,
        isFavorite: true,
        comments: [
          {
            id: 1,
            body: "3 aydır kullanıyorum, oyun performansı bu fiyata gayet iyi.",
            authorUsername: "aslıhan",
            createdAt: "2026-09-17T12:00:00Z",
            canDelete: false,
          },
        ],
      },
      {
        id: 2,
        name: "Poco X6 Pro",
        price: 14999,
        imageUrl: null,
        productUrl: "https://example.com/poco-x6-pro",
        features: ["Dimensity 8300 Ultra", "120Hz AMOLED ekran", "IP54 koruma"],
        attributes: { RAM: "12 GB", Depolama: "512 GB", İşlemci: "Dimensity 8300 Ultra" },
        worthCount: 33,
        notWorthCount: 13,
        worthRatio: 72,
        showResults: true,
        userVote: null,
        isCheapest: false,
        isFavorite: false,
        comments: [],
      },
    ],
  },
  {
    id: 2,
    title: "Uzaktan çalışma için hangi kulaklık?",
    description: null,
    category: "kulaklik",
    usagePurpose: "is",
    budgetTier: "premium",
    authorUsername: "melis",
    createdAt: "2026-09-15T08:30:00Z",
    expiresAt: null,
    isActive: true,
    isExpired: false,
    hideResultsUntilVote: true,
    viewCount: 210,
    totalVotes: 34,
    todayVotes: 3,
    minPrice: 8999,
    maxPrice: 11999,
    products: [
      {
        id: 3,
        name: "Sony WH-1000XM5",
        price: 11999,
        imageUrl: null,
        productUrl: null,
        features: ["Sektörün en iyi ANC'si", "30 saat pil ömrü"],
        attributes: { Bağlantı: "Bluetooth 5.2", Ağırlık: "250g" },
        worthCount: 20,
        notWorthCount: 2,
        worthRatio: 91,
        showResults: false,
        userVote: null,
        isCheapest: false,
        isFavorite: true,
        comments: [],
      },
      {
        id: 4,
        name: "Bose QC45",
        price: 8999,
        imageUrl: null,
        productUrl: null,
        features: ["Hafif tasarım", "Dengeli ses profili"],
        attributes: { Bağlantı: "Bluetooth 5.1", Ağırlık: "238g" },
        worthCount: 9,
        notWorthCount: 3,
        worthRatio: 75,
        showResults: false,
        userVote: null,
        isCheapest: true,
        isFavorite: false,
        comments: [],
      },
    ],
  },
  {
    id: 3,
    title: "Video düzenleme için laptop önerisi",
    description: "Premiere Pro ile ağır 4K projeler üzerinde çalışacağım.",
    category: "laptop",
    usagePurpose: "is",
    budgetTier: "premium",
    authorUsername: "kaan",
    createdAt: "2026-09-10T14:00:00Z",
    expiresAt: "2026-09-20T14:00:00Z",
    isActive: false,
    isExpired: true,
    hideResultsUntilVote: false,
    viewCount: 950,
    totalVotes: 210,
    todayVotes: 0,
    minPrice: 45999,
    maxPrice: 62999,
    products: [
      {
        id: 5,
        name: "MacBook Pro 14 M3",
        price: 62999,
        imageUrl: null,
        productUrl: null,
        features: ["M3 Pro çip", "18 saate kadar pil ömrü"],
        attributes: { RAM: "18 GB", Depolama: "512 GB SSD" },
        worthCount: 140,
        notWorthCount: 20,
        worthRatio: 88,
        showResults: true,
        userVote: "worth",
        isCheapest: false,
        isFavorite: true,
        comments: [],
      },
      {
        id: 6,
        name: "ASUS ProArt Studiobook",
        price: 45999,
        imageUrl: null,
        productUrl: null,
        features: ["RTX 4060", "OLED ekran"],
        attributes: { RAM: "32 GB", Depolama: "1 TB SSD" },
        worthCount: 38,
        notWorthCount: 12,
        worthRatio: 76,
        showResults: true,
        userVote: null,
        isCheapest: true,
        isFavorite: false,
        comments: [],
      },
    ],
  },
];

export function getPollById(id: number): Poll | undefined {
  return mockPolls.find((poll) => poll.id === id);
}
